<?php
$dadosCategorias=array("pao"=>"Pão","doces"=>"Doces","bolos"=>"Bolos","salgados"=>"Salgados","bebidas"=>"Bebidas","sorvetes"=>"Sorvete");
$dadosProdutos=array(
                    0=>array("nome"=>"bolo de chocolate",
                    "imagem"=>"bolo-de-chocolate.jpg",
                    "preco"=>50,
                    "descrição"=>"bolo de chocolate feito com chocolate",
                    "categoria"=>"bolos"),
                    1=>array("nome"=>"bolo de morango",
                    "imagem"=>"bolo-de-morango.jpg",
                    "descrição"=>"bolo de morango feito com morango",
                    "preco"=>60,
                    "categoria"=>"bolos"),
                    2=>array("nome"=>"bolo de ouro",
                    "imagem"=>"bolo-de-ouro.jpg",
                    "descrição"=>"bolo de ouro feito com ouro",
                    "preco"=>1000,
                    "categoria"=>"bolos"),
                    3=>array("nome"=>"bolo de nozes",
                    "imagem"=>"bolo-de-nozes.jpg",
                    "descrição"=>"bolo de nozes feito com nozes",
                    "preco"=>100,
                    "categoria"=>"bolos"),
                    4=>array("nome"=>"bolo de terra",
                    "imagem"=>"bolo-de-terra.jpg",
                    "descrição"=>"bolo de terra feito com terra",
                    "preco"=>10,
                    "categoria"=>"bolos"),
                    5=>array("nome"=>"bolo de banana",
                    "imagem"=>"bolo-de-banana.jpg",
                    "descrição"=>"bolo de banana feito com banana",
                    "preco"=>30,
                    "categoria"=>"bolos"),
                    6=>array("nome"=>"bolo de repolho",
                    "imagem"=>"bolo-de-repolho.jpg",
                    "descrição"=>"bolo de repolho feito com repolho",
                    "preco"=>50,
                    "categoria"=>"bolos"),
                    7=>array("nome"=>"bolo de aveia",
                    "imagem"=>"bolo-de-aveia.jpg",
                    "descrição"=>"bolo de aveia feito com aveia",
                    "preco"=>60,
                    "categoria"=>"bolos"),
                    8=>array("nome"=>"bolo de churros",
                    "imagem"=>"bolo-de-churros.jpg",
                    "descrição"=>"bolo de churros feito com churros",
                    "preco"=>100,
                    "categoria"=>"bolos"),
                    9=>array("nome"=>"bolo de nutella",
                    "imagem"=>"bolo-de-nutella.jpg",
                    "descrição"=>"bolo de nutella feito com nutella",
                    "preco"=>150,
                    "categoria"=>"bolos"),
);
$dadosReceita = array(
                    0=> array('titulo'=>'bolo de chocolate',
                    'imagem'=>'bolo-de-chocolate.jpg',
                    'descricao'=>'receita incrivel de bolo de chocolate',
                    'receita'=>'30 ovos <br> 50 barras de chocolate <br> 5 litros de leite <br> 2 pote de whey <br> 2 pitada de açucar',
                    'video'=>'https://www.youtube.com/embed/zCUDoCsBewk'),
                    1=> array('titulo'=>'bolo de morango',
                    'imagem'=>'bolo-de-morango.jpg',
                    'descricao'=>'receita incrivel de bolo de morango',
                    'receita'=>'30 ovos <br> 50 morangos <br> 5 litros de leite <br> 2 pote de whey <br> 2 pitada de açucar',
                    'video'=>'https://www.youtube.com/embed/zCUDoCsBewk'),
                    2=> array('titulo'=>'bolo de banana',
                    'imagem'=>'bolo-de-banana.jpg',
                    'descricao'=>'receita incrivel de bolo de banana',
                    'receita'=>'30 ovos <br> 50 bananas <br> 5 litros de leite <br> 2 pote de whey <br> 2 pitada de açucar',
                    'video'=>'https://www.youtube.com/embed/zCUDoCsBewk'),
                    3=> array('titulo'=>'bolo de churros',
                    'imagem'=>'bolo-de-churros.jpg',
                    'descricao'=>'receita incrivel de bolo de churros',
                    'receita'=>'30 ovos <br> 50 churros <br> 5 litros de leite <br> 2 pote de whey <br> 2 pitada de açucar',
                    'video'=>'https://www.youtube.com/embed/zCUDoCsBewk'),
                    4=> array('titulo'=>'bolo de ouro',
                    'imagem'=>'bolo-de-ouro.jpg',
                    'descricao'=>'receita incrivel de bolo de ouro',
                    'receita'=>'30 ovos <br> 50 kilos de ouro <br> 5 litros de leite <br> 2 pote de whey <br> 2 pitada de açucar',
                    'video'=>'https://www.youtube.com/embed/zCUDoCsBewk'),
                    5=> array('titulo'=>'bolo de repolho',
                    'imagem'=>'bolo-de-repolho.jpg',
                    'descricao'=>'receita incrivel de bolo de repolho',
                    'receita'=>'30 ovos <br> 50 repolhos <br> 5 litros de leite <br> 2 pote de whey <br> 2 pitada de açucar',
                    'video'=>'https://www.youtube.com/embed/zCUDoCsBewk'),
);
?>